gometalinter.config
s3plugin/s3plugin.go

This linter ensures that we check the error on functions that return an
error. This will help prevent bugs where we assume that a function such
as Chmod or Open is successful, but forget to check that no error is
returned.
In cases where we do intentionally want to ignore the error, we will now
need to assign it to an empty identifier, such as _ = os.Chmod().
Authored-by: Chris Hajas <chajas@pivotal.io>

Add errcheck linter

---

README.md
s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

The S3 plugin now supports specifying a custom endpoint instead of an
AWS region to backup/restore to/from a storage solution that implements
the S3 protocol.
Additionally, validate the configuration file prior to attempting to
connect to the S3 server.
Co-authored-by: Chris Hajas <chajas@pivotal.io>
Co-authored-by: Amil Khanzada <akhanzada@pivotal.io>

Add support for using custom endpoint

---

Gopkg.lock
Gopkg.toml
README.md
s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

Adds a parameter, encryption, to the config. By default, we enable SSL
encryption. If the user specifies this value as "off", SSL encryption
will be disabled.
Authored-by: Chris Hajas <chajas@pivotal.io>

Add support for disabling SSL encryption

---

gpbackup_s3_plugin.go

The output will now state this utility should not be explicitly called
by a user.
Authored-by: Chris Hajas <chajas@pivotal.io>

Modify --help flag output

---

s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

When inside EC2, or if any of the other [default credential chain options are configured](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials), you don't need to set credentials manually.

Using default creds if none provided

---

s3plugin/s3plugin.go

The verbosity can now be turned on by setting "debug: true" in the pluginconfig file

Set Log verbosity based on plugin config

---

gpbackup_s3_plugin.go
s3plugin/s3plugin.go

The performance testing job for S3 would backup and restore 10-50GB of data using parallel and serial versions of directory API.
Examples:
```
/usr/local/gpdb/bin/gpbackup_s3_plugin restore_directory ~/s3config.yaml backups/20200131/20200131144745
cat ~/gpAdminLogs/gprestore_20200316.log
20200316:16:27:53 gprestore:ljain:Lavs-MacBook-Pro.local:010345-[DEBUG]:-Restore Directory 'backups/20200131/20200131144745' from S3
20200316:16:27:53 gprestore:ljain:Lavs-MacBook-Pro.local:010345-[DEBUG]:-S3 Location = s3://gpbackup-s3-plugin-test/backups/backups/20200131/20200131144745
20200316:16:27:53 gprestore:ljain:Lavs-MacBook-Pro.local:010345-[DEBUG]:-File 'gpbackup_0_20200131144745_2218753.gz' = 2456698614 bytes
20200316:16:27:53 gprestore:ljain:Lavs-MacBook-Pro.local:010345-[DEBUG]:-File …
```

Introduce backupDirectory and restoreDirectory

---

s3plugin/backup.go
s3plugin/restore.go
s3plugin/s3plugin.go

* Change upload concurrency to 6.
* The s3-plugin-performance job shows an improvement of around 50% for uploads

Use smaller chunk size during uploads

---

s3plugin/backup.go

When executed for metadata only, the call fails on the segments because the backup data directories do not exist. This behavior did not manifest during regular backup command because `gpbackup` creates those directories before calling the plugin.

Fix regression in S3 plugin SetupPluginForBackup (metadata only)

---

gpbackup_s3_plugin.go
s3plugin/backup.go
s3plugin/restore.go
s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

We don't want to give users the ability to change what gets logged. All
debug statements are logged by default. This also changes the logging
location to gpbackup_s3_plugin.
Authored-by: Kevin Yeap <kyeap@pivotal.io>

Remove debug configfiguration

---

README.md
s3plugin/s3plugin.go

Exposed a new configuration property for s3 plugin to support configuring proxy.
`http_proxy` which should contain the proxy url of the form `http://username:password@proxy.example.com:1234`
Use `http.Client` as a means to set the proxy address.

Added support to accept http_proxy for s3 plugin

---

go.mod
go.sum
s3plugin/backup.go
s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

- upload_concurrency - int value to configure
concurrent upload of multi part file. Should
be less then max_concurrent_requests. Default
value is 6.
- upload_chunk_size - bytesize format ("5B", "10KB", "1MB" etc)
to specify chunk size when upload multi part file.
Should be more then 5MB to avoid "part size must be at least
5242880 bytes" error and not less then filesize/10000 to avoid
"exceeded total allowed configured MaxUploadParts" error.
Default value is 10Mb.
Authored-by: Kate Dontsova <edontsova@pivotal.io>
- [] Run the unit tests with `make test`
- [] Run the plugin test bench as described [here](https://github.com/greenplum-db/gpbackup/tree/master/plugins)
- [] Describe in the PR if any [documentation](https://gpdb.docs.pivotal.io/latest/admin_guide/managing/backup-s3-plugin.html) …

Adds upload parameters to config

---

s3plugin/restore.go
s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

Previous download implementation (with the growing size of download
chunk and download buffers the size of the number of chunks) used to
cause unbounded growth of memory usage and, therefore, restore process
failure.
New logic implies fixed chunk size and usage of memory pool the size
of the number of workers as download buffers. Chunk size and the number
of workers can be adjusted in config file.
- restore_max_concurrent_requests - int value to configure
  download concurrency (number of workers). Default: 6.
- restore_multipart_chunksize - bytesize format ("5B", "10KB", "1MB"
etc) to specify download chunk size. Default: 10MB.

Add memory pool and download parameters

---

s3plugin/s3plugin.go

Connect to Amazon S3 using dual-stack endpoints. Amazon S3 dual-stack
endpoints support requests to S3 buckets over IPv6 and IPv4.  When you
make a request to a dual-stack endpoint, the bucket URL resolves to an
IPv6 or an IPv4 address.

Support connection to Amazon S3 over IPv6

---

s3plugin/backup.go
s3plugin/restore.go
s3plugin/s3plugin.go

Increased the default upload and download chunk size to 500MB.
Modified restore_data behavior to make sure we always conform with chunk
size and concurrency. We will have as many download workers as the
configured concurrency value and similarly the buffer size that each
worker downloads will be based on the configured chunk size.
Each individual worker will implicitly set the s3 manager's downloader
chunksize as well to the same value and concurrency to 1 as each worker
handles only one chunk at a time.
Added additional debug logging messages.
- [] Run the unit tests with `make test`
- [] Run the plugin test bench as described [here](https://github.com/greenplum-db/gpbackup/tree/master/plugins)
- [] Describe in the PR if any [documentation](https://gpdb.docs.pivotal.io/latest/admin_guide/ …

Updated upload/download default chunk size and restore data changes

---

s3plugin/backup.go
s3plugin/restore.go
s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

There have been cases where an option was misspelled resulting in
unexpected behavior. Previously, s3 plugin would ignore unknown yaml
options. Now s3 plugin will error out immediately if it finds any
unknown configurations.

Do not allow unknown plugin configurations

---

s3plugin/s3plugin.go

During backup, segment host specific configuration files are created and
this includes `pgport` and `backup_plugin_version` as additional fields in
the options. Now that plugins can only allow specific set of options,
we've added these 2 fields as well.

Added pgport and backup_plugin_version to plugin options

---

s3plugin/s3plugin.go
s3plugin/s3plugin_test.go

This is to fix a regression caused by my commit 7d329a3. In that commit,
the wrong validation for the encryption option was implemented. The
validation was supposed to ensure that the only valid values of "on" or
"off" were specified, however it was incorrectly checking for the values
"yes" and "no". The appriopriate changes to the test and regression have
been made.
s3 plugin reference regression commit:
https://github.com/greenplum-db/gpbackup-s3-plugin/commit/7d329a3
In the docs
https://gpdb.docs.pivotal.io/43310/admin_guide/managing/backup-s3-plugin.html
The encryption description will need to be updated
```
encryption
Optional. Enable or disable use of Secure Sockets Layer (SSL) when 
connecting to an S3 location. Default value is on, use connections that 
are secured with SSL. Set …
```

Fix encryption validation to check for "on" and "off"

---

Makefile

GPDB7+ will ship with gpsync instead of gpscp, so prefer that if available. Fall back to gpscp if needed.

Update makefile to use gpsync

---

s3plugin/s3plugin.go

The previous PR added new CLI commands, but neglected to bump the API version.  Update that now.

Update api version

---

s3plugin/backup.go
s3plugin/restore.go
s3plugin/s3plugin.go

In the case of using an endpoint directly, instead of relying on AWS to resolve it, the bucket name gets duplicated in the HTTP path, which means that all of the backups/restores have an extra "root" folder of the bucket name. This breaks things like gpbackup_manager, as well as contravening user expectations.
To solve this, we manually edit the path when uploading or downloading a file with a config that contains a populated Endpoint field.

Alter path for endpoint configs

---

s3plugin/backup.go
s3plugin/restore.go
s3plugin/s3plugin.go

AWS SDK only duplicates the bucket name if fed hostname for an endpoint. So add a check whether it's an IP address and do not remove bucketname from path if it is.

Only remove bucket name if not an IP

---

s3plugin/backup.go
s3plugin/restore.go
s3plugin/s3plugin.go

10a4b72d - Only remove bucket name if not an IP
bce4362  - Alter path for endpoint configs
Commits 10a4b72d and bce4362 will be reverted because they cause a
`NoSuchBucket` error when using an endpoint to access a bucket on s3
compliant object storage such as Minio. These two commits have the
assumption that the bucket is automatically appended to the URI when the
endpoint option is used to access the bucket. This is not true as local
testing with Minio starts to fail. The original issue that caused these
two commits seemed to be an error where the URI built using endpoint by
AWS SDK GO was appending the bucket_name twice. I am unable to reproduce
the original duplicate bucket_name seen previously, and these commits
are causing backups and restore when using endpoints to fail. I am …

Fix `NoSuchBucket` using reverts
